### ISSUE TITLE
Error deactivating package

### ISSUE THREAD

**Issue by Hativ** [WhoIsJingJing/atom-certificate-view#1]
When deactivating atom-certificate-view in Atom the developer console is showing the following error:

> package.coffee:516 Error deactivating package 'atom-certificate-view' TypeError: this.atomCertificateView.destroy is not a function
>     at Object.deactivate (/home/username/.atom/packages/atom-certificate-view/lib/main.js:28:30)
>     at Package.module.exports.Package.deactivate (/usr/lib/atom/src/package.js:808:20)
>     at PackageManager.module.exports.PackageManager.deactivatePackage (/usr/lib/atom/src/package-manager.js:725:12)
>     at /usr/lib/atom/src/package-manager.js:359:21
>     at /usr/lib/atom/src/config.js:642:20
>     at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
>     at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
>     at Config.module.exports.Config.emitChangeEvent (/usr/lib/atom/src/config.js:833:29)
>     at Config.module.exports.Config.setRawValue (/usr/lib/atom/src/config.js:619:19)
>     at Config.module.exports.Config.set (/usr/lib/atom/src/config.js:234:14)
>     at Config.module.exports.Config.pushAtKeyPath (/usr/lib/atom/src/config.js:368:12)
>     at Package.module.exports.Package.disable (/usr/lib/atom/src/package.js:86:26)
>     at PackageManager.module.exports.PackageManager.disablePackage (/usr/lib/atom/src/package-manager.js:185:16)
>     at HTMLButtonElement.enablementButtonClickHandler (/usr/lib/atom/node_modules/settings-view/lib/package-card.js:355:25)module.exports.Package.deactivate @ package.coffee:516module.exports.PackageManager.deactivatePackage @ package-manager.coffee:575(anonymous function) @ package-manager.coffee:357(anonymous function) @ config.coffee:977module.exports.Emitter.simpleDispatch @ emitter.js:25module.exports.Emitter.emit @ emitter.js:141module.exports.Config.emitChangeEvent @ config.coffee:1096module.exports.Config.setRawValue @ config.coffee:964module.exports.Config.set @ config.coffee:668module.exports.Config.pushAtKeyPath @ config.coffee:787module.exports.Package.disable @ package.coffee:67module.exports.PackageManager.disablePackage @ package-manager.coffee:212enablementButtonClickHandler @ package-card.js:237

PS: atom-certificate-view works also great on Linux

**Comment by mingjunyang** [comment]
@Hativ3  maybe I know how to fix it, I will try later.
